#!/usr/bin/env bash
set -euo pipefail

DOCKER_APP="${HOME}/Applications/Docker.app"
DOCKER_BIN="${DOCKER_APP}/Contents/Resources/bin/docker"
COMPOSE_BIN="${DOCKER_APP}/Contents/Resources/cli-plugins/docker-compose"

if [[ "${1:-}" == "compose" ]]; then
  shift
  exec "${COMPOSE_BIN}" "$@"
fi

exec "${DOCKER_BIN}" "$@"
